### ISSUE TITLE
token movement

### ISSUE THREAD

**Issue by keinkurt** [pchab/frosthaven-ability-cards#4]
Hi,

first of all, thanks for you work! It's much more easier to play with your app, instead of play with the cards at Tabletop Simulator.

I've a suggesting to change the handling of the token movements to make it more like in real. I would set the token on the first slot, after the card is played and the on click on the token it will move to the next slot and finally if the token left the last slot the card would be discard/lost.

I hope you are on my side ;)

Best regards,
Christian

**Comment by pchab** [comment]
Hi Christian,

I'm glad you're enjoying the app.

I implemented the token feature when I added the Drifter class, and this class gimmick is that it can move token backwards too. If I implement your suggestion, I need to make it so that drifters can also move the token backwards.

**Comment by keinkurt** [comment]
Ok, I understand. That's right, for Drifter it's a good feature, that you can click on the empty slots to move the token to them. But as I understand it right, on every token card, the starts on the first slot. So, I think it's better to place the token on the first slot, after the card is played.

**Comment by pchab** [comment]
Hi Christian,

I've opened a [PR](https://github.com/pchab/frosthaven-ability-cards/pull/5) Can you test it and tell me what you think ?
You can use the preview deployment [here](https://vercel.live/link/frosthaven-ability-cards-git-feat-acti-c66b63-pierre4s-projects.vercel.app)

**Comment by pchab** [comment]
I just added you on vercel, you should be able to view the preview build now.

**Comment by keinkurt** [comment]
It's works very good, I like the new mechanism. But one thing you have to in mind, almost all persistence cards can activly discard/lost, even though not all slots are passed.

**Comment by pchab** [comment]
Added the remove effect action on cards with slots
