### ISSUE TITLE
Card selection to play area

### ISSUE THREAD

**Issue by keinkurt** [pchab/frosthaven-ability-cards#9]
first of all, thanks for this app, it's great and helpful your work!

I have a suggestion for the card selection from the hand to the play area. Maybe it's better to have the select card button at the left side.

thanks and greetings

**Comment by pchab** [comment]
https://frosthaven-ability-cards-git-9-card-se-f625c5-pierre4s-projects.vercel.app?_vercel_share=OXGjq97JHwTaf22C510C0gQgbeXvoy7K

**Comment by pchab** [comment]
Let me know what you think.

**Comment by keinkurt** [comment]
Thanks, now the card selection feels better.
